param(
  [string]$BrainRoot = "$env:USERPROFILE\AI-Network-Lab-Brain"
)

Set-Location $BrainRoot

$CurrentState = Join-Path $BrainRoot "00_CURRENT_STATE"
$BrainOS = Join-Path $BrainRoot "99_BRAIN_OS"

New-Item -ItemType Directory -Force $CurrentState | Out-Null
New-Item -ItemType Directory -Force $BrainOS | Out-Null

$MarkdownFiles = Get-ChildItem -Path $BrainRoot -Recurse -File -Filter "*.md" |
  Where-Object {
    $_.FullName -notmatch "\\.git\\" -and
    $_.FullName -notmatch "\\.obsidian\\"
  }

$GeneratedAt = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$Index = @()
$Index += "# AUTO GENERATED BRAIN INDEX"
$Index += ""
$Index += "Generated at: $GeneratedAt"
$Index += ""
$Index += "Total Markdown files: $($MarkdownFiles.Count)"
$Index += ""
$Index += "---"
$Index += ""

foreach ($file in $MarkdownFiles | Sort-Object FullName) {
  $relative = $file.FullName.Replace($BrainRoot + "\", "")
  $title = Select-String -Path $file.FullName -Pattern "^# " -SimpleMatch:$false -ErrorAction SilentlyContinue | Select-Object -First 1

  if ($title) {
    $cleanTitle = $title.Line.Trim()
  } else {
    $cleanTitle = "# " + $file.BaseName
  }

  $Index += "## $relative"
  $Index += ""
  $Index += "Title: $cleanTitle"
  $Index += ""
}

$Index | Set-Content ".\00_CURRENT_STATE\AUTO_INDEX.md" -Encoding UTF8

$Summary = @"
# BRAIN BUILD REPORT

Generated at: $GeneratedAt

## Files scanned

$($MarkdownFiles.Count)

## Generated files

- 00_CURRENT_STATE/AUTO_INDEX.md

## Rule

This file is generated by:

99_BRAIN_OS/BUILD_BRAIN.ps1

Do not manually edit generated files unless necessary.
"@

$Summary | Set-Content ".\00_CURRENT_STATE\BUILD_REPORT.md" -Encoding UTF8

Write-Host "Brain build completed."
Write-Host "Markdown files scanned: $($MarkdownFiles.Count)"
Write-Host "Generated: 00_CURRENT_STATE\AUTO_INDEX.md"
Write-Host "Generated: 00_CURRENT_STATE\BUILD_REPORT.md"
